"""update id system

Revision ID: 72a6d5e6469b
Revises: 
Create Date: 2024-05-17 03:47:06.919266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a6d5e6469b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iphons',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('shop',
    sa.Column('shop_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shop_id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_table('price',
    sa.Column('price_id', sa.String(), nullable=False),
    sa.Column('shop_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['iphons.model_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['iphons.model_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.shop_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.shop_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('shop')
    op.drop_table('iphons')
    # ### end Alembic commands ###
