"""migration

Revision ID: acb7d5ac7b47
Revises: 04b1a28e994b
Create Date: 2024-04-30 01:02:25.660377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb7d5ac7b47'
down_revision: Union[str, None] = '04b1a28e994b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('price',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['iphons.model_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.shop_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('shop')
    # ### end Alembic commands ###
