version: '3.8'

services:
  app:
    container_name: my_project_app
    build: .
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 && alembic upgrade head
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: on-failure
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
          - POSTGRES_USER=${POSTGRESS_DB_USER}
          - POSTGRES_PASSWORD=${POSTGRESS_DB_PASSWORD}
          - POSTGRES_DB=${POSTGRESS_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 10s
      retries: 120

volumes:
  postgres_data:
