version: '3.8'

services:
  app:
    container_name: my_project_app
    build: .
    depends_on:
      - postgres
    command: alembic upgrade head  && uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./app:/src/app
      - ./alembic.ini:/path/inside/container/alembic.ini # Добавляем том с alembic.ini
    ports:
      - ${APP_HOST_PORT}:8000
    restart: on-failure
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    environment:
          - POSTGRES_USER="postgres"
          - POSTGRES_PASSWORD="postgres"
          - POSTGRES_DB="postgres"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
