version: '3.8'

services:
  app:
    container_name: my_project_app
    build: .
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: on-failure
    env_file:
      - .env

#  postgres:
#    image: postgres:13
#    environment:
#          - POSTGRES_USER=app
#          - POSTGRES_PASSWORD=123qwe
#          - POSTGRES_DB=movies_database
#    volumes:
#      - ./movies_database.ddl:/movies_database.ddl:ro
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
#      interval: 5s
#      timeout: 10s
#      retries: 120

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRESS_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRESS_DB_NAME}

volumes:
  postgres_data:
